### ISSUE TITLE
Use sphinx book theme as default package theme.

### ISSUE THREAD

**Issue by Pugio** [executablebooks/markdown-it-docutils#23]
### Describe the problem/need and solution

`markdown-it-docutils` bundles parts of the Furo theme by default. This is odd to me, as when I try to render things (e.g. admonitions) using `jupyterlab-myst` it doesn't look the same as when using `jupyter-book`. Since all of these packages are part of the `executablebooks` project, wouldn't it make sense to be consistent in the default theme used amongst all packages/tools?

I'm happy to expand this issue into a work proposal if this makes sense.

**Comment by chrisjsewell** [comment]
Honestly I would not really be interested in this. This is entirely separate from jupyter-book and furo's css is much better and more complete than sphinx-book-theme's, in fact sphinx-book-theme is currently undergoing lots of underlying changes to be more like furo.

**Comment by Pugio** [comment]
Thank you for the insight. Furo is nice, but it's automatic dark theme support seems a bit lacking (by default):

<img width="859" alt="image" src="https://user-images.githubusercontent.com/286180/153089896-3a48d843-2fa6-4670-8d98-c1b468f769fe.png">

I'll close this issue and just make my tweaks down the line.

**Comment by chrisjsewell** [comment]
Obviously, it would be ideal if you could simply "plug-in" your own css, within JupyterLab.

But yeh, as it stands, it would just be a lot of work to change the css, and might end up being a waste of time, given the fact of how in flux sphinx-book-theme is
