### ISSUE TITLE
Rename this repository to `markdown-it-directives`

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/markdown-it-docutils#25]
### Describe the problem/need and solution

**Context**
This repository draws its name from the `docutils` project in Python, which is a big inspiration for MyST Markdown's syntax. In particular, roles and directives.

In addition, it seems that the scope of this repository is explicitly for `docutils-style roles and directives` (from the README).

While `docutils` is obviously the inspiration here, and we should give it credit and recognition in our README etc, it is also not a well-known project, especially outside of the Python ecosystem. Moreover, for those who **do** know it, the name `docutils` may not evoke ideas about well-run and stable packages 😅

**Proposed action**
I propose that we rename this repository to `markdown-it-directives`. This would be more descriptive, because `directive` is a more generally-known term, and it matches more cleanly onto the functionality of this repository. It focuses the repository's name on the feature that it brings, rather than the package that inspired the feature.

Note that `roles` is technically a sibling of `directives`, not a subset of it, but I think that semantically they are close enough that it wouldn't be confusing for somebody to use `markdown-it-directives` and expect that in-line roles come along for the ride.

If instead we think it is crucial that this package be connected to `docutils`, then I'm fine leaving the name as-is, it's not a huge deal, but I think that if this connection is incidential instead of crucial, we should rename it to make it easier for others to recognize and remember (and to avoid dissuading anybody out there that doesn't want to touch something branded `docutils` with a 10 foot pole haha).

**Comment by choldgraf** [comment]
Argh, I just head from @rowanc1 that this already exists:

https://www.npmjs.com/package/markdown-it-directive

So maybe `directives` is not the right name. But still, I feel like a name that is more tied to the functionality we wish to enable, and less tied to `docutils`, would help others understand and discover the repository...

**Comment by chrisjsewell** [comment]
This is already being discussed in https://github.com/executablebooks/mystjs/issues/34

Its very much tied to docutils specific implementation of roles and directives

**Comment by choldgraf** [comment]
ok I'll close this and go over there

**Comment by chrisjsewell** [comment]
yep no worries 👍
